-- More 3D Services
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('b3d002', '3D Product Visualization', 'Transform your product ideas into stunning 3D visualizations', '3D & 2D Content Creation', 350, 700, 1200, 5, 7, 10, '1 product render', '3 product angles', '360° turntable, AR-ready', ARRAY['1 product render'], ARRAY['3 product angles', 'Advanced materials'], ARRAY['360° turntable', 'AR-ready'], 2, 4, 6, '5-10 days', 0, false, ARRAY['$BONK'], ARRAY['3D Visualization', 'Product']),
('b3d003', 'Token Launch Animation', 'Eye-catching animations for your token launch', '3D & 2D Content Creation', 400, 800, 1400, 5, 7, 10, 'Logo animation (10s)', 'Logo + Promo (30s)', 'Full package with social clips', ARRAY['Logo animation'], ARRAY['Logo', 'Promo video'], ARRAY['Logo', 'Promo', 'Social clips'], 3, 5, 7, '5-10 days', 0, true, ARRAY['$PEPE', '$WIF'], ARRAY['Animation', 'Launch']),
('b3d003', '2D/3D Motion Graphics', 'Unique motion graphics for explainer videos', '3D & 2D Content Creation', 350, 650, 1100, 4, 6, 8, '15-second graphic', '30-second with sound', '60-second full production', ARRAY['15-second graphic'], ARRAY['30-second with sound'], ARRAY['60-second production', 'Custom music'], 3, 5, 8, '4-8 days', 0, false, ARRAY['$POPCAT'], ARRAY['Motion Graphics', 'Social Media']),
('b3d004', 'NFT Collection (10K PFPs)', 'End-to-end NFT collection creation', '3D & 2D Content Creation', 3500, 7000, 12000, 21, 30, 45, '10K collection, Basic traits', '10K collection, Advanced traits', '10K collection, Premium traits + animations', ARRAY['10K collection', 'Basic traits'], ARRAY['10K collection', 'Advanced traits', 'Rarity config'], ARRAY['10K collection', 'Premium traits', 'Animations', 'Smart contracts'], 3, 5, 10, '21-45 days', 0, true, ARRAY['$BLUR', '$LOOKS'], ARRAY['NFT', 'PFP', 'Collection']),
('b3d004', 'Custom 1/1 NFT Artwork', 'Hand-crafted unique NFT artwork', '3D & 2D Content Creation', 500, 1000, 2000, 7, 10, 14, '1 unique NFT', '3 unique NFTs', '5 unique artworks', ARRAY['1 unique NFT'], ARRAY['3 unique NFTs'], ARRAY['5 unique artworks', 'Variations'], 2, 4, 6, '7-14 days', 0, false, ARRAY['$X2Y2'], ARRAY['NFT', '1/1', 'Art']);

-- More KOL Services
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bkol001', 'Community AMA Hosting', 'Professional AMA sessions for your project', 'KOLs & Influencers', 2000, 3500, 6000, 2, 3, 5, '1-hour AMA', '2-hour AMA with promo', '3-hour AMA with recording + clips', ARRAY['1-hour AMA'], ARRAY['2-hour AMA', 'Pre-promotion'], ARRAY['3-hour AMA', 'Recording', 'Clips'], 0, 1, 2, '2-5 days', 0, false, ARRAY['$MEW'], ARRAY['AMA', 'Community']),
('bkol002', 'Memecoin Launch Strategy', 'Complete memecoin launch strategy', 'KOLs & Influencers', 3000, 6000, 12000, 5, 7, 10, 'Content calendar (1 week)', 'Campaign strategy (2 weeks)', 'Full launch strategy (4 weeks)', ARRAY['Content calendar'], ARRAY['Campaign strategy'], ARRAY['Full launch strategy', 'Ongoing support'], 2, 3, 5, '5-10 days', 0, true, ARRAY['$MOG'], ARRAY['Memecoin', 'Launch']),
('bkol003', 'DeFi Project Coverage', 'In-depth DeFi project coverage', 'KOLs & Influencers', 2500, 5000, 9000, 5, 7, 10, '1 thread, 1 tutorial', '3 threads, 2 tutorials, 1 video', '5 threads, 4 tutorials, 3 videos', ARRAY['1 thread', '1 tutorial'], ARRAY['3 threads', '2 tutorials', '1 video'], ARRAY['5 threads', '4 tutorials', '3 videos'], 2, 3, 4, '5-10 days', 0, false, ARRAY['$BASE', '$AERO'], ARRAY['DeFi', 'Coverage']),
('bkol004', 'Influencer Network Campaign', 'Coordinate 50+ crypto influencers', 'KOLs & Influencers', 8000, 15000, 30000, 7, 10, 14, '10 influencers', '25 influencers', '50+ influencers', ARRAY['10 influencers'], ARRAY['25 influencers', 'Campaign strategy'], ARRAY['50+ influencers', 'Full management'], 2, 3, 5, '7-14 days', 0, true, ARRAY['$PEPE', '$SHIB'], ARRAY['Influencer', 'Campaign']);

-- More Dev Services  
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bdev001', 'DeFi Protocol Development', 'Build custom DeFi protocols', 'Script Development', 8000, 15000, 30000, 30, 45, 60, 'Core protocol', 'Full protocol with frontend', 'Complete platform + audit', ARRAY['Core protocol'], ARRAY['Full protocol', 'Frontend'], ARRAY['Complete platform', 'Advanced features', 'Audit'], 5, 8, 15, '30-60 days', 0, true, ARRAY['$COMP'], ARRAY['DeFi', 'Protocol']),
('bdev002', 'NFT Marketplace Development', 'Build your NFT marketplace', 'Script Development', 5000, 10000, 20000, 30, 45, 60, 'Basic marketplace', 'Advanced marketplace', 'Full-featured with admin', ARRAY['Basic marketplace'], ARRAY['Auctions', 'Offers'], ARRAY['Analytics', 'Admin tools'], 5, 8, 15, '30-60 days', 0, false, ARRAY['$BLUR'], ARRAY['NFT', 'Marketplace']),
('bdev003', 'Token Presale System', 'Complete token launch infrastructure', 'Script Development', 2000, 4000, 8000, 10, 14, 21, 'Basic presale', 'Presale with vesting', 'Full launch system', ARRAY['Basic presale'], ARRAY['Presale', 'Vesting'], ARRAY['Anti-bot', 'Auto-liquidity'], 3, 5, 10, '10-21 days', 0, true, ARRAY['$FLOKI'], ARRAY['Presale', 'Launch']),
('bdev004', 'Solana Program Development', 'High-performance Solana programs', 'Script Development', 3000, 6000, 12000, 14, 21, 30, 'Basic program', 'Advanced program', 'Complex with optimizations', ARRAY['Basic program'], ARRAY['Multiple instructions'], ARRAY['Optimizations', 'Security'], 4, 6, 10, '14-30 days', 0, false, ARRAY['$JUP', '$BONK'], ARRAY['Solana', 'Rust']);

-- Marketing Services
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bmkt001', 'Token Launch Marketing', 'Comprehensive marketing campaign', 'Marketing & Growth', 2500, 5000, 10000, 14, 21, 30, 'Marketing strategy', 'Full campaign', 'Complete with ads', ARRAY['Strategy', 'Social plan'], ARRAY['Full campaign', 'Influencer outreach'], ARRAY['Paid ads', 'Analytics'], 3, 5, 8, '14-30 days', 0, true, ARRAY['$DEGEN', '$BRETT'], ARRAY['Marketing', 'Launch']),
('bmkt001', 'Community Growth Package', 'Grow to 10K+ members', 'Marketing & Growth', 1500, 3000, 6000, 30, 45, 60, 'Growth strategy', 'Strategy + content', 'Full campaign', ARRAY['Growth strategy'], ARRAY['Content calendar'], ARRAY['Engagement tactics'], 3, 5, 8, '30-60 days', 0, false, ARRAY['$TOSHI'], ARRAY['Community', 'Growth']),
('bmkt002', 'Memecoin Viral Marketing', 'Viral marketing for memecoins', 'Marketing & Growth', 2000, 4000, 8000, 7, 14, 21, '1 week strategy', '2 week campaign', '4 week extended', ARRAY['Viral strategy'], ARRAY['Full campaign'], ARRAY['Extended', 'Raids'], 3, 5, 10, '7-21 days', 0, true, ARRAY['$PEPE', '$WIF'], ARRAY['Memecoin', 'Viral']),
('bmkt003', 'Data-Driven Growth', 'Analytics-based optimization', 'Marketing & Growth', 1800, 3500, 7000, 14, 21, 30, 'Analytics setup', 'Funnel optimization', 'Ongoing optimization', ARRAY['Analytics', 'Audit'], ARRAY['Full funnel'], ARRAY['A/B testing'], 2, 4, 8, '14-30 days', 0, false, ARRAY['$BASE'], ARRAY['Analytics', 'Growth']);

-- Graphic Design Services
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bgfx001', 'Brand Identity Package', 'Complete brand identity', 'Graphic Design', 1200, 2500, 5000, 10, 14, 21, 'Logo + Colors', 'Logo, Colors, Typography', 'Complete brand book', ARRAY['Logo', 'Colors'], ARRAY['Logo', 'Colors', 'Typography'], ARRAY['Brand book', 'Templates'], 3, 5, 10, '10-21 days', 0, true, ARRAY['$BLUR'], ARRAY['Branding', 'Logo']),
('bgfx001', 'Social Media Graphics', 'Custom social media graphics', 'Graphic Design', 400, 800, 1500, 5, 7, 10, '10 graphics', '25 graphics + templates', '50+ graphics', ARRAY['10 graphics'], ARRAY['25 graphics', 'Templates'], ARRAY['50+ graphics', 'Ongoing'], 2, 4, 6, '5-10 days', 0, false, ARRAY['$OPENSEA'], ARRAY['Social Media']),
('bgfx002', 'DApp UI/UX Design', 'Beautiful DApp interfaces', 'Graphic Design', 2000, 4000, 8000, 14, 21, 30, 'UI for 5 screens', 'Full UI/UX 15 screens', 'Complete design system', ARRAY['5 screens'], ARRAY['15 screens'], ARRAY['Design system', 'Prototypes'], 4, 6, 10, '14-30 days', 0, true, ARRAY['$UNI'], ARRAY['UI/UX', 'DApp']),
('bgfx003', 'Animated Logo & Branding', 'Animated brand elements', 'Graphic Design', 600, 1200, 2400, 7, 10, 14, 'Animated logo', 'Logo + Brand animation', 'Full animated suite', ARRAY['Logo animation'], ARRAY['Brand package'], ARRAY['Full suite'], 3, 5, 8, '7-14 days', 0, true, ARRAY['$BRETT'], ARRAY['Animation', 'Logo']);

-- Video Editing
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bvid001', 'Launch Video Production', 'Professional launch videos', 'Video Editing', 800, 1500, 3000, 7, 10, 14, '60-second video', '90-second with graphics', '2-minute cinematic', ARRAY['60-second'], ARRAY['90-second', 'Graphics'], ARRAY['2-minute', 'Voiceover'], 3, 5, 8, '7-14 days', 0, true, ARRAY['$PRIME'], ARRAY['Video', 'Launch']),
('bvid001', 'Tutorial Videos', 'Educational tutorial videos', 'Video Editing', 600, 1200, 2400, 5, 7, 10, '1 tutorial (2-3 min)', '3 tutorials', '5+ tutorials', ARRAY['1 tutorial'], ARRAY['3 tutorials'], ARRAY['5+ tutorials', 'Graphics'], 2, 4, 6, '5-10 days', 0, false, ARRAY['$UNI'], ARRAY['Tutorial', 'Education']),
('bvid002', 'Cinematic Showcase', 'High-end showcase videos', 'Video Editing', 1500, 3000, 6000, 10, 14, 21, '2-minute showcase', '3-minute with interviews', '5-minute documentary', ARRAY['2-minute'], ARRAY['3-minute', 'Interviews'], ARRAY['5-minute documentary'], 3, 5, 8, '10-21 days', 0, true, ARRAY['$APE'], ARRAY['Cinematic', 'Showcase']),
('bvid003', 'Viral Short-Form Content', 'TikToks, Reels, Shorts', 'Video Editing', 300, 600, 1200, 3, 5, 7, '5 short videos', '15 short videos', '30 short videos', ARRAY['5 videos'], ARRAY['15 videos'], ARRAY['30 videos', 'Trending audio'], 2, 3, 5, '3-7 days', 0, true, ARRAY['$PEPE', '$DOGE'], ARRAY['Short-Form', 'Viral']);

-- Social Media
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bsoc001', 'Social Media Management', 'Complete social media management', 'Social Media Management', 1500, 3000, 6000, 30, 30, 30, '3 posts/week', '7 posts/week', 'Daily posts + stories', ARRAY['3 posts/week'], ARRAY['7 posts/week'], ARRAY['Daily posts', 'Stories', 'Full management'], 0, 0, 0, 'Monthly', 0, true, ARRAY['$BASE'], ARRAY['Social Media', 'Management']),
('bsoc001', 'Content Creation Package', 'Custom content creation', 'Social Media Management', 800, 1500, 3000, 7, 14, 30, '20 posts/month', '40 posts/month', '60+ posts/month', ARRAY['20 posts'], ARRAY['40 posts', 'Scheduling'], ARRAY['60+ posts', 'Full strategy'], 2, 3, 5, '7-30 days', 0, false, ARRAY['$BRETT'], ARRAY['Content', 'Social']),
('bsoc002', 'Community Engagement', 'Daily community engagement', 'Social Media Management', 600, 1200, 2400, 30, 30, 30, '1 hour/day', '2 hours/day', '4+ hours/day', ARRAY['1 hour/day'], ARRAY['2 hours/day'], ARRAY['4+ hours/day'], 0, 0, 0, 'Monthly', 0, false, ARRAY['$TOSHI'], ARRAY['Engagement', 'Community']);

-- Mods & Raiders
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bmod001', 'Discord Moderation', '24/7 Discord moderation', 'Mods & Raiders', 800, 1500, 3000, 30, 30, 30, 'Basic (8hrs/day)', 'Standard (16hrs/day)', 'Premium 24/7', ARRAY['8hrs/day'], ARRAY['16hrs/day'], ARRAY['24/7 coverage'], 0, 0, 0, 'Monthly', 0, true, ARRAY['$DEGEN'], ARRAY['Moderation', 'Discord']),
('bmod001', 'Event Hosting', 'Community events', 'Mods & Raiders', 400, 800, 1500, 7, 7, 7, '2 events/month', '4 events/month', '8 events/month', ARRAY['2 events'], ARRAY['4 events'], ARRAY['8 events', 'Full production'], 1, 2, 3, 'Weekly', 0, false, ARRAY['$TOSHI'], ARRAY['Events', 'Community']),
('bmod002', 'Raid Coordination', 'Strategic community raids', 'Mods & Raiders', 500, 1000, 2000, 7, 14, 30, '4 raids/month', '8 raids/month', '15+ raids/month', ARRAY['4 raids'], ARRAY['8 raids'], ARRAY['15+ raids', 'Strategy'], 1, 2, 3, '7-30 days', 0, true, ARRAY['$PEPE'], ARRAY['Raids', 'Growth']);

-- Volume
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bvol001', 'Volume Generation', 'Organic volume generation', 'Volume Services', 2000, 5000, 10000, 7, 14, 30, '$50K volume', '$250K volume', '$1M+ volume', ARRAY['$50K trading'], ARRAY['$250K trading'], ARRAY['$1M+ sustained'], 1, 2, 3, '7-30 days', 0, true, ARRAY['$UNI'], ARRAY['Volume', 'Trading']),
('bvol001', 'Liquidity Provision', 'Professional LP service', 'Volume Services', 1500, 3000, 6000, 7, 14, 30, 'Basic LP', 'Advanced LP', 'Full market making', ARRAY['Basic LP'], ARRAY['LP', 'Rebalancing'], ARRAY['Full market making'], 1, 2, 3, '7-30 days', 0, false, ARRAY['$SUSHI'], ARRAY['Liquidity', 'MM']),
('bvol002', 'Launch Volume Support', 'Healthy launch volume', 'Volume Services', 3000, 6000, 12000, 3, 5, 7, '24-hour support', '3-day support', '7-day support', ARRAY['24-hour'], ARRAY['3-day'], ARRAY['7-day', 'Anti-bot'], 1, 2, 3, '3-7 days', 0, true, ARRAY['$AERO'], ARRAY['Launch', 'Volume']);

-- Strategy
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bstr001', 'Strategy Consultation', 'Comprehensive strategic consultation', 'Strategy Consulting', 1500, 3000, 6000, 7, 14, 21, '2-hour consult', '4 hours + strategy', '8+ hours + full plan', ARRAY['2-hour', 'Report'], ARRAY['4 hours', 'Detailed doc'], ARRAY['8+ hours', 'Full plan'], 2, 3, 5, '7-21 days', 0, true, ARRAY['$UNI'], ARRAY['Strategy', 'Consulting']),
('bstr001', 'Go-to-Market Strategy', 'GTM strategy for launch', 'Strategy Consulting', 2000, 4000, 8000, 10, 14, 21, 'Basic GTM plan', 'Detailed GTM', 'Complete playbook', ARRAY['Basic GTM'], ARRAY['Detailed GTM', 'Tactics'], ARRAY['Complete playbook', 'Execution'], 2, 3, 5, '10-21 days', 0, false, ARRAY['$COMP'], ARRAY['Go-to-Market', 'Strategy']),
('bstr002', 'Tokenomics Design', 'Professional tokenomics design', 'Strategy Consulting', 2500, 5000, 10000, 14, 21, 30, 'Basic model', 'Advanced with simulations', 'Complete with whitepaper', ARRAY['Basic model'], ARRAY['Advanced', 'Simulations'], ARRAY['Complete', 'Whitepaper section'], 3, 5, 8, '14-30 days', 0, true, ARRAY['$CURVE'], ARRAY['Tokenomics', 'Economics']);

-- Documentation
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bdoc001', 'Whitepaper Writing', 'Professional whitepaper writing', 'Documentation & Paperwork', 1500, 3000, 6000, 14, 21, 30, 'Basic (10-15 pages)', 'Advanced (20-30 pages)', 'Comprehensive (40+ pages)', ARRAY['10-15 pages'], ARRAY['20-30 pages'], ARRAY['40+ pages', 'Technical details'], 3, 5, 10, '14-30 days', 0, true, ARRAY['$ETH'], ARRAY['Whitepaper', 'Documentation']),
('bdoc001', 'Technical Documentation', 'Developer documentation', 'Documentation & Paperwork', 800, 1500, 3000, 7, 14, 21, 'Basic API docs', 'Full technical docs', 'Complete developer portal', ARRAY['API docs'], ARRAY['Full docs'], ARRAY['Developer portal', 'Examples'], 2, 4, 6, '7-21 days', 0, false, ARRAY['$LINK'], ARRAY['Technical', 'Docs']),
('bdoc002', 'Legal Compliance', 'Comprehensive compliance docs', 'Documentation & Paperwork', 2000, 4000, 8000, 14, 21, 30, 'Compliance review', 'Full package with ToS', 'Complete legal package', ARRAY['Review'], ARRAY['Full package', 'ToS'], ARRAY['Multi-jurisdiction'], 2, 3, 5, '14-30 days', 0, true, ARRAY['$USDC'], ARRAY['Legal', 'Compliance']);

-- Grants
INSERT INTO services (builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, delivery_time, psx_required, featured, token_tickers, tags) VALUES
('bgrn001', 'Grant Application Writing', 'Professional grant applications', 'Grants & Funding', 1000, 2000, 4000, 14, 21, 30, '1 application', '3 applications', '5+ applications', ARRAY['1 grant'], ARRAY['3 grants'], ARRAY['5+ grants', 'Ongoing'], 2, 3, 5, '14-30 days', 0, true, ARRAY['$OP', '$BASE'], ARRAY['Grants', 'Funding']),
('bgrn001', 'Ecosystem Fund Strategy', 'Strategic fund guidance', 'Grants & Funding', 800, 1500, 3000, 7, 14, 21, '1-hour consult', 'Full analysis', 'Complete strategy', ARRAY['Consultation', 'Roadmap'], ARRAY['Ecosystem analysis', 'Applications'], ARRAY['Complete strategy', 'Execution'], 2, 3, 5, '7-21 days', 0, false, ARRAY['$MATIC'], ARRAY['Ecosystem', 'Strategy']),
('bgrn002', 'VC Pitch Deck', 'Compelling pitch decks', 'Grants & Funding', 1200, 2500, 5000, 10, 14, 21, 'Basic (10 slides)', 'Professional (15 slides)', 'Complete package', ARRAY['10 slides'], ARRAY['15 slides'], ARRAY['Full package', 'Financials'], 3, 5, 8, '10-21 days', 0, true, ARRAY['$AVAX'], ARRAY['Pitch Deck', 'VC']);
