-- Clear existing sample data
DELETE FROM services WHERE builder_id IN (SELECT id FROM builders);
DELETE FROM builders;

-- 3D & 2D Content Creation Builders (3d-content)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, software_3d, render_engines, style_specialties, animation_expertise) VALUES
('b3d001', '0x3D1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Alex Rivera', '3D Character Artist | Unreal Engine Pro', 'Specialized in hyper-realistic character modeling for Web3 gaming projects. 8+ years creating memorable avatars and game assets.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex3d', true, '3D & 2D Content Creation', '4.95', 127, 156, '2-6 hours', ARRAY['Blender', 'Unreal Engine', 'ZBrush', 'Substance Painter', 'Character Design'], ARRAY['$PRIME', '$GALA', '$BEAM', '$RONIN'], 'available', '85', true, ARRAY['Blender', 'Maya', 'ZBrush'], ARRAY['Unreal Engine', 'Unity', 'Cycles'], ARRAY['Characters', 'Environments', 'Weapons'], true),
('b3d002', '0x3D2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Maya Chen', 'Environment Artist | Cinematic Renders', '3D environment artist creating immersive worlds for memecoins and NFT collections. Featured in 50+ successful launches.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=mayachen', true, '3D & 2D Content Creation', '4.88', 94, 112, '4-12 hours', ARRAY['Cinema 4D', 'Octane', '3ds Max', 'Environment Design', 'Asset Creation'], ARRAY['$APE', '$DEGEN', '$BONK'], 'available', '75', false, ARRAY['Cinema 4D', '3ds Max', 'Houdini'], ARRAY['Octane', 'Redshift', 'V-Ray'], ARRAY['Environments', 'Architecture', 'Props'], false),
('b3d003', '0x3D3' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Jordan Blake', '2D/3D Hybrid Animator | Motion Graphics', 'Creating eye-catching animations for token launches and marketing campaigns. Specialist in memecoin visual identity.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordanblake', false, '3D & 2D Content Creation', '4.92', 78, 89, '6-24 hours', ARRAY['After Effects', 'Blender', 'Animation', 'Motion Design', 'Video Editing'], ARRAY['$PEPE', '$WIF', '$POPCAT'], 'busy', '68', true, ARRAY['Blender', 'Cinema 4D'], ARRAY['Eevee', 'Octane'], ARRAY['Animation', 'Motion Graphics'], true),
('b3d004', '0x3D4' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Sophia Martinez', 'NFT Collection Specialist | PFP Expert', 'Crafted 100+ successful NFT collections with combined trading volume of 50,000+ ETH. Expert in trait systems and generative art.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sophianft', true, '3D & 2D Content Creation', '4.97', 203, 247, '1-4 hours', ARRAY['Photoshop', 'Illustrator', 'Procreate', 'NFT Design', 'Trait Systems'], ARRAY['$BLUR', '$LOOKS', '$X2Y2'], 'available', '92', true, ARRAY['Blender', 'ZBrush'], ARRAY['Cycles'], ARRAY['Characters', 'PFPs'], false);

-- KOLs & Influencers (kols)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, twitter_handle, twitter_followers, instagram_handle, instagram_followers, telegram_handle, telegram_members, engagement_rate, content_niches, brand_partnerships) VALUES
('bkol001', '0xKOL1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Crypto King Carlos', 'Top 50 Crypto KOL | 500K+ Followers', 'Influencer with proven track record of successful token launches. Specialized in memecoin marketing and community building.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=carlos', true, 'KOLs & Influencers', '4.89', 156, 189, '2-8 hours', ARRAY['Twitter Growth', 'Community Building', 'Content Creation', 'Token Marketing'], ARRAY['$WIF', '$POPCAT', '$MEW', '$BONK'], 'available', '250', true, '@cryptokingcarlos', 547000, '@cryptokingc', 123000, '@carloscrypto', 45000, '8.7', ARRAY['Memecoins', 'NFTs', 'DeFi', 'Gaming'], ARRAY['Blur', 'Magic Eden', '1inch', 'Uniswap']),
('bkol002', '0xKOL2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Luna Moonwalker', 'Memecoin Queen | Viral Tweet Master', 'Expert at creating viral content that drives engagement. Launched 30+ tokens to 7-figure market caps through strategic content.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=luna', true, 'KOLs & Influencers', '4.91', 134, 167, '4-12 hours', ARRAY['Viral Marketing', 'Meme Creation', 'Twitter Threads', 'Community Management'], ARRAY['$DEGEN', '$BRETT', '$MOG'], 'available', '200', true, '@lunamoonwalker', 312000, '@luna_crypto', 89000, '@lunawalks', 28000, '12.3', ARRAY['Memecoins', 'Community', 'Viral Content'], ARRAY['Tensor', 'Raydium', 'Jupiter']),
('bkol003', '0xKOL3' || lpad(floor(random() * 1000000)::text, 6, '0'), 'TechSavvy Sam', 'DeFi & Gaming Influencer | 200K+ Engaged Community', 'Tech-focused crypto influencer specializing in Base ecosystem projects. Known for in-depth analysis and community engagement.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=techsam', false, 'KOLs & Influencers', '4.85', 92, 108, '6-24 hours', ARRAY['Technical Analysis', 'DeFi Coverage', 'Project Reviews', 'AMA Hosting'], ARRAY['$BASE', '$AERO', '$VIRTUAL'], 'busy', '150', false, '@techsavvysam', 218000, '@techsam_eth', 54000, NULL, NULL, '9.1', ARRAY['DeFi', 'Gaming', 'Infrastructure'], ARRAY['Base', 'Aerodrome', 'Synthetix']),
('bkol004', '0xKOL4' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Meme Master Mike', 'Memecoin Specialist | Launch Expert', 'Successfully promoted 100+ memecoin launches with average 10x returns. Master of community hype and FOMO generation.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=mikememe', true, 'KOLs & Influencers', '4.93', 178, 214, '1-6 hours', ARRAY['Memecoin Marketing', 'Launch Strategy', 'Hype Creation', 'Influencer Network'], ARRAY['$PEPE', '$SHIB', '$FLOKI', '$WOJAK'], 'available', '275', true, '@mememas termi ke', 689000, '@mikememecoin', 167000, '@mikememes', 72000, '11.5', ARRAY['Memecoins', 'Viral Marketing', 'Launch Campaigns'], ARRAY['PumpFun', 'DexScreener', 'DexTools']);

-- Script Development (development)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, programming_languages, blockchain_frameworks, github_profile, certifications) VALUES
('bdev001', '0xDEV1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Vitalik Jr', 'Senior Smart Contract Engineer | Audited $500M+ TVL', 'Solidity expert with 6+ years building battle-tested DeFi protocols. Specialized in gas optimization and security best practices.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=vitalikjr', true, 'Script Development', '4.98', 234, 278, '2-6 hours', ARRAY['Solidity', 'Hardhat', 'Foundry', 'Smart Contract Security', 'Gas Optimization'], ARRAY['$UNI', '$AAVE', '$COMP'], 'available', '150', true, ARRAY['Solidity', 'JavaScript', 'TypeScript', 'Rust'], ARRAY['Hardhat', 'Foundry', 'OpenZeppelin', 'Ethers.js'], 'github.com/vitalikjr', ARRAY['Certified Blockchain Developer', 'Smart Contract Security Specialist']),
('bdev002', '0xDEV2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Satoshi Tanaka', 'Full-Stack Web3 Dev | DApp Architect', 'End-to-end blockchain developer creating seamless Web3 experiences. Built 50+ production dApps with millions in trading volume.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=satoshit', true, 'Script Development', '4.94', 187, 219, '4-12 hours', ARRAY['React', 'Next.js', 'Wagmi', 'RainbowKit', 'Smart Contracts', 'Backend APIs'], ARRAY['$OP', '$ARB', '$BASE'], 'available', '125', false, ARRAY['JavaScript', 'TypeScript', 'Solidity', 'Python'], ARRAY['Wagmi', 'Viem', 'Ethers.js', 'Web3.js'], 'github.com/satoshitanaka', ARRAY['AWS Certified', 'Full-Stack Web3 Developer']),
('bdev003', '0xDEV3' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Ada Lovelace', 'Token Contract Specialist | Launch Expert', 'Created 200+ successful token contracts with advanced features. Expert in tokenomics, anti-bot mechanisms, and launch strategies.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=adal', true, 'Script Development', '4.96', 312, 367, '1-4 hours', ARRAY['Token Development', 'Anti-Bot Systems', 'Liquidity Locks', 'Tax Mechanisms', 'Presale Contracts'], ARRAY['$SAFEMOON', '$SHIB', '$FLOKI'], 'available', '135', true, ARRAY['Solidity', 'JavaScript', 'Python'], ARRAY['Hardhat', 'Remix', 'OpenZeppelin'], 'github.com/adalovelace', ARRAY['Solidity Expert', 'Token Economics Specialist']),
('bdev004', '0xDEV4' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Rust Master Ryan', 'Solana Developer | High-Performance Programs', 'Solana specialist building lightning-fast programs. Expert in Anchor framework and optimizing transaction speeds.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ryanrust', false, 'Script Development', '4.91', 143, 172, '6-24 hours', ARRAY['Rust', 'Anchor', 'Solana Web3.js', 'Program Optimization'], ARRAY['$JUP', '$JTO', '$BONK', '$WIF'], 'busy', '140', false, ARRAY['Rust', 'TypeScript', 'Python'], ARRAY['Anchor', 'Solana Web3.js', 'Metaplex'], 'github.com/rustmasterryan', ARRAY['Solana Certified Developer']);

-- Marketing & Growth (marketing)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, marketing_platforms, growth_strategies, avg_roi) VALUES
('bmkt001', '0xMKT1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Growth Guru Gary', 'Web3 Marketing Strategist | 10x Growth Expert', 'Scaled 50+ crypto projects from launch to 8-figure market caps. Data-driven approach with proven ROI.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=gary', true, 'Marketing & Growth', '4.92', 167, 198, '4-12 hours', ARRAY['Growth Marketing', 'Community Building', 'Influencer Outreach', 'Launch Strategy', 'Analytics'], ARRAY['$DEGEN', '$BRETT', '$TOSHI'], 'available', '110', true, ARRAY['Twitter', 'Discord', 'Telegram', 'Farcaster'], ARRAY['Influencer Marketing', 'Community Growth', 'Content Strategy', 'Paid Ads'], '847.50'),
('bmkt002', '0xMKT2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Viral Vicky', 'Memecoin Marketing Queen | Community Expert', 'Specialist in creating viral marketing campaigns for memecoins. Built communities from 0 to 100K+ members.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=vicky', true, 'Marketing & Growth', '4.88', 134, 156, '2-8 hours', ARRAY['Viral Marketing', 'Meme Creation', 'Community Management', 'Content Calendar'], ARRAY['$PEPE', '$WIF', '$POPCAT'], 'available', '95', true, ARRAY['Twitter', 'Reddit', 'TikTok', 'Instagram'], ARRAY['Viral Content', 'Meme Marketing', 'Community Raids'], '623.25'),
('bmkt003', '0xMKT3' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Analytics Andy', 'Data-Driven Growth Hacker | Conversion Expert', 'Using data analytics to optimize every aspect of token marketing. Expert in attribution modeling and funnel optimization.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=andy', false, 'Marketing & Growth', '4.95', 98, 114, '6-24 hours', ARRAY['Data Analytics', 'A/B Testing', 'Conversion Optimization', 'Marketing Automation'], ARRAY['$BASE', '$AERO'], 'busy', '120', false, ARRAY['Google Analytics', 'Dune Analytics', 'Mixpanel'], ARRAY['Data Analysis', 'Performance Marketing', 'Attribution'], '512.75');

-- Graphic Design (graphic-design)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending) VALUES
('bgfx001', '0xGFX1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Design Diva Diana', 'Brand Identity Specialist | 300+ Web3 Brands', 'Creating memorable visual identities for crypto projects. Expert in logo design, brand guidelines, and marketing materials.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=diana', true, 'Graphic Design', '4.94', 212, 256, '4-12 hours', ARRAY['Logo Design', 'Brand Identity', 'Illustration', 'Marketing Collateral', 'Social Media Graphics'], ARRAY['$BLUR', '$LOOKS', '$OPENSEA'], 'available', '75', true),
('bgfx002', '0xGFX2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Pixel Perfect Pete', 'UI/UX Designer | Web3 Interface Expert', 'Crafting beautiful, intuitive interfaces for DeFi protocols and NFT platforms. User-centric design philosophy.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=pete', true, 'Graphic Design', '4.91', 178, 203, '2-8 hours', ARRAY['UI/UX Design', 'Figma', 'Prototyping', 'User Research', 'Design Systems'], ARRAY['$UNI', '$AAVE'], 'available', '85', false),
('bgfx003', '0xGFX3' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Motion Master Max', 'Motion Designer | Animated Branding', 'Bringing brands to life with captivating animations. Specialist in animated logos, explainer videos, and social media content.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=max', false, 'Graphic Design', '4.89', 143, 167, '6-24 hours', ARRAY['Motion Graphics', 'After Effects', 'Animation', 'Video Editing'], ARRAY['$DEGEN', '$BRETT'], 'busy', '82', true);

-- Video Editing (video-editor)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, editing_software, editing_specialties, video_types) VALUES
('bvid001', '0xVID1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Editor Eddie', 'Professional Video Editor | 1000+ Projects', 'High-quality video editing for crypto marketing campaigns, tutorials, and social content. Fast turnaround guaranteed.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=eddie', true, 'Video Editing', '4.93', 267, 312, '2-6 hours', ARRAY['Premiere Pro', 'Final Cut Pro', 'DaVinci Resolve', 'Motion Graphics', 'Color Grading'], ARRAY['$PRIME', '$GALA'], 'available', '65', true, ARRAY['Premiere Pro', 'After Effects', 'DaVinci Resolve'], ARRAY['Marketing Videos', 'Tutorials', 'Social Content'], ARRAY['Explainers', 'Commercials', 'Social Media']),
('bvid002', '0xVID2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Cinematic Clara', 'Cinematic Video Producer | Storytelling Expert', 'Creating compelling narratives through video. Specialist in project showcases and launch videos that convert.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=clara', true, 'Video Editing', '4.96', 189, 218, '4-12 hours', ARRAY['Cinematic Editing', 'Storytelling', 'Sound Design', 'Visual Effects'], ARRAY['$APE', '$AZUKI'], 'available', '78', false, ARRAY['Final Cut Pro', 'Premiere Pro', 'After Effects'], ARRAY['Cinematic', 'Storytelling', 'Brand Videos'], ARRAY['Brand Stories', 'Launches', 'Showcases']),
('bvid003', '0xVID3' || lpad(floor(random() * 1000000)::text, 6, '0'), 'TikTok Tommy', 'Short-Form Content King | Viral Video Specialist', 'Expert at creating viral short-form content for TikTok, Instagram Reels, and Twitter. 50M+ combined views.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tommy', false, 'Video Editing', '4.87', 156, 187, '1-4 hours', ARRAY['Short-Form Editing', 'Viral Content', 'CapCut', 'Trend Analysis'], ARRAY['$PEPE', '$WIF', '$DOGE'], 'available', '55', true, ARRAY['CapCut', 'Premiere Pro'], ARRAY['Short-Form', 'Viral Content', 'Social Media'], ARRAY['TikToks', 'Reels', 'Shorts']);

-- Social Media Management (social-media)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, platforms_managed) VALUES
('bsoc001', '0xSOC1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Social Sarah', 'Social Media Manager | Multi-Platform Expert', 'Managing social media for 20+ successful crypto projects. Expert in content strategy, scheduling, and engagement.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah', true, 'Social Media Management', '4.91', 178, 209, '2-8 hours', ARRAY['Content Strategy', 'Social Media Management', 'Community Engagement', 'Analytics'], ARRAY['$BASE', '$DEGEN'], 'available', '60', true, ARRAY['Twitter', 'Instagram', 'Facebook', 'LinkedIn', 'TikTok']),
('bsoc002', '0xSOC2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Content King Kevin', 'Content Creator | Engagement Specialist', 'Creating engaging content that drives conversations and builds communities. 5+ years in crypto social media.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=kevin', false, 'Social Media Management', '4.88', 134, 156, '4-12 hours', ARRAY['Content Creation', 'Copywriting', 'Graphic Design', 'Video Editing'], ARRAY['$BRETT', '$TOSHI'], 'busy', '55', false, ARRAY['Twitter', 'Discord', 'Telegram']);

-- Mods & Raiders (mods-raiders)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, platforms_managed, max_community_size, raid_coordination, event_hosting) VALUES
('bmod001', '0xMOD1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Moderator Mike', 'Professional Discord Moderator | 500K+ Members Managed', 'Experienced community moderator with proven track record managing large crypto communities. Available 24/7.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=mikemod', true, 'Mods & Raiders', '4.95', 234, 278, '1-4 hours', ARRAY['Community Moderation', 'Conflict Resolution', 'Event Hosting', 'Bot Management'], ARRAY['$DEGEN', '$BRETT', '$TOSHI'], 'available', '45', true, ARRAY['Discord', 'Telegram'], 500000, true, true),
('bmod002', '0xMOD2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Raid Master Rachel', 'Community Raid Coordinator | Engagement Expert', 'Organizing strategic community raids that drive engagement and growth. Expert at building hype and momentum.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=rachel', true, 'Mods & Raiders', '4.92', 167, 198, '2-6 hours', ARRAY['Raid Coordination', 'Community Management', 'Twitter Engagement', 'Growth Hacking'], ARRAY['$PEPE', '$WIF'], 'available', '50', true, ARRAY['Twitter', 'Discord', 'Telegram'], 250000, true, false);

-- Volume Services (volume)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending, trading_experience, dex_expertise, cex_expertise) VALUES
('bvol001', '0xVOL1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Volume Vince', 'Professional Market Maker | $100M+ Volume Generated', 'Providing organic-looking volume for new token launches. Expert across all major DEXs and CEXs.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=vince', true, 'Volume Services', '4.89', 145, 178, '4-12 hours', ARRAY['Market Making', 'Volume Generation', 'Liquidity Provision', 'Trading Strategies'], ARRAY['$UNI', '$SUSHI'], 'available', '200', true, 8, ARRAY['Uniswap', 'PancakeSwap', 'Raydium', 'Jupiter'], ARRAY['Binance', 'Coinbase', 'Kraken']),
('bvol002', '0xVOL2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Liquidity Larry', 'DEX Volume Specialist | Launch Support', 'Ensuring smooth token launches with strategic volume provision. Specialist in preventing pump-and-dumps.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=larry', false, 'Volume Services', '4.91', 112, 134, '6-24 hours', ARRAY['DEX Trading', 'Volume Strategies', 'Launch Support'], ARRAY['$AERO', '$VELODROME'], 'busy', '180', false, 6, ARRAY['Uniswap V3', 'Aerodrome', 'Velodrome'], ARRAY['Binance', 'OKX']);

-- Strategy Consulting (strategy-consulting)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending) VALUES
('bstr001', '0xSTR1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Strategy Steve', 'Web3 Strategic Consultant | 100+ Projects Advised', 'Helping crypto projects define winning strategies. From tokenomics to go-to-market, I guide projects to success.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=steve', true, 'Strategy Consulting', '4.97', 189, 223, '12-24 hours', ARRAY['Strategic Planning', 'Tokenomics Design', 'Go-to-Market Strategy', 'Competitive Analysis'], ARRAY['$UNI', '$AAVE', '$COMP'], 'available', '250', true),
('bstr002', '0xSTR2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Tokenomics Tina', 'Tokenomics Expert | Economic Model Designer', 'Designing sustainable tokenomics that align incentives and drive long-term value. PhD in Economics.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tina', true, 'Strategy Consulting', '4.95', 156, 187, '24-48 hours', ARRAY['Tokenomics Design', 'Economic Modeling', 'Incentive Structures', 'Sustainability'], ARRAY['$CURVE', '$CVX'], 'busy', '275', false);

-- Documentation & Paperwork (documentation)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending) VALUES
('bdoc001', '0xDOC1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Whitepaper Wendy', 'Technical Writer | Crypto Documentation Expert', 'Writing clear, compelling whitepapers and technical documentation. 150+ projects documented with clarity and precision.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=wendy', true, 'Documentation & Paperwork', '4.93', 167, 198, '24-48 hours', ARRAY['Technical Writing', 'Whitepaper Creation', 'Documentation', 'Research'], ARRAY['$ETH', '$BTC'], 'available', '85', true),
('bdoc002', '0xDOC2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Legal Liam', 'Crypto Legal Consultant | Compliance Specialist', 'Ensuring your project meets all legal requirements. Expert in crypto regulations across multiple jurisdictions.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=liam', true, 'Documentation & Paperwork', '4.96', 134, 156, '48-72 hours', ARRAY['Legal Compliance', 'Regulatory Analysis', 'Terms of Service', 'Privacy Policy'], ARRAY['$USDC', '$USDT'], 'busy', '200', false);

-- Grants & Funding (grants-funding)
INSERT INTO builders (id, wallet_address, name, headline, bio, profile_image, verified, category, rating, review_count, completed_projects, response_time, skills, token_tickers, availability, hourly_rate, is_trending) VALUES
('bgrn001', '0xGRN1' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Grant Guru Gloria', 'Grant Writing Specialist | $50M+ Secured', 'Expert at securing grants and funding for crypto projects. Successful applications to major ecosystem funds.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=gloria', true, 'Grants & Funding', '4.98', 98, 112, '48-72 hours', ARRAY['Grant Writing', 'Funding Strategy', 'Pitch Decks', 'Application Management'], ARRAY['$OP', '$ARB', '$BASE'], 'available', '150', true),
('bgrn002', '0xGRN2' || lpad(floor(random() * 1000000)::text, 6, '0'), 'Fundraising Frank', 'VC Relations Expert | Ecosystem Fund Navigator', 'Connecting crypto projects with the right investors and grant programs. Network across all major ecosystems.', 'https://api.dicebear.com/7.x/avataaars/svg?seed=frank', false, 'Grants & Funding', '4.91', 76, 89, '24-48 hours', ARRAY['VC Outreach', 'Pitch Preparation', 'Ecosystem Grants', 'Investor Relations'], ARRAY['$MATIC', '$AVAX'], 'available', '125', false);

-- Services for 3D & 2D Content Builders
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('s3d001', 'b3d001', 'Hyper-Realistic 3D Character Design', 'Create stunning 3D characters for your Web3 game or NFT project. Includes high-poly modeling, texturing, rigging, and basic animations.', '3D & 2D Content Creation', 450, 850, 1500, 7, 10, 14, 'High-poly 3D model, Basic textures, T-pose', 'Fully textured model, Advanced rigging, 3 animations', 'Game-ready model, Full animation set, Multiple LODs, Source files', 2, 4, 6, ARRAY['https://picsum.photos/seed/3dchar1/800/600', 'https://picsum.photos/seed/3dchar2/800/600', 'https://picsum.photos/seed/3dchar3/800/600'], ARRAY['$PRIME', '$GALA', '$BEAM'], ARRAY['3D Modeling', 'Character Design', 'Game Assets', 'NFT'], '7-14 days', true),
('s3d002', 'b3d001', '3D Weapon & Item Design', 'Design unique weapons and items for your game or metaverse project. High-quality assets optimized for real-time rendering.', '3D & 2D Content Creation', 300, 600, 1000, 5, 7, 10, '1 weapon/item model', '3 weapon/item models with variations', '5+ models, Multiple materials, Particle effects', 2, 3, 5, ARRAY['https://picsum.photos/seed/weapon1/800/600', 'https://picsum.photos/seed/weapon2/800/600'], ARRAY['$PRIME', '$RONIN'], ARRAY['3D Modeling', 'Game Assets', 'Weapons', 'Items'], '5-10 days', false),
('s3d003', 'b3d002', 'Cinematic 3D Environment Design', 'Breathtaking 3D environments for marketing renders, trailers, or game levels. Perfect for token launches and NFT showcases.', '3D & 2D Content Creation', 600, 1200, 2200, 10, 14, 21, 'Basic environment scene, 2 render angles', 'Detailed environment, 5 render angles, Lighting setup', 'Highly detailed scene, Unlimited angles, Animation, Source files', 2, 3, 5, ARRAY['https://picsum.photos/seed/env1/800/600', 'https://picsum.photos/seed/env2/800/600', 'https://picsum.photos/seed/env3/800/600'], ARRAY['$APE', '$DEGEN'], ARRAY['3D Environments', 'Rendering', 'Marketing'], '10-21 days', true),
('s3d004', 'b3d002', '3D Product Visualization', 'Transform your product ideas into stunning 3D visualizations. Perfect for pitches, marketing, and investor presentations.', '3D & 2D Content Creation', 350, 700, 1200, 5, 7, 10, '1 product render, Basic lighting', '3 product angles, Advanced materials', '360° turntable, Multiple variations, AR-ready', 2, 4, 6, ARRAY['https://picsum.photos/seed/prod1/800/600', 'https://picsum.photos/seed/prod2/800/600'], ARRAY['$BONK'], ARRAY['3D Visualization', 'Product Design'], '5-10 days', false),
('s3d005', 'b3d003', 'Token Launch Animation Package', 'Eye-catching animations for your token launch including logo reveal, promo video, and social media teasers.', '3D & 2D Content Creation', 400, 800, 1400, 5, 7, 10, 'Logo animation (10s)', 'Logo + Promo video (30s)', 'Full package: Logo, Promo (60s), Social clips', 3, 5, 7, ARRAY['https://picsum.photos/seed/anim1/800/600', 'https://picsum.photos/seed/anim2/800/600'], ARRAY['$PEPE', '$WIF'], ARRAY['Animation', 'Token Launch', 'Marketing'], '5-10 days', true),
('s3d006', 'b3d003', '2D/3D Hybrid Motion Graphics', 'Blend 2D and 3D elements for unique motion graphics perfect for explainer videos and social media content.', '3D & 2D Content Creation', 350, 650, 1100, 4, 6, 8, '15-second motion graphic', '30-second motion graphic with sound', '60-second full production with custom music', 3, 5, 8, ARRAY['https://picsum.photos/seed/motion1/800/600'], ARRAY['$POPCAT'], ARRAY['Motion Graphics', '2D/3D', 'Social Media'], '4-8 days', false),
('s3d007', 'b3d004', 'Complete NFT Collection (10K PFPs)', 'End-to-end NFT collection creation including trait design, generation, metadata, and rarity configuration.', '3D & 2D Content Creation', 3500, 7000, 12000, 21, 30, 45, '10K collection, Basic traits (20 layers)', '10K collection, Advanced traits (40 layers), Rarity config', '10K collection, Premium traits (60+ layers), Custom animations, Smart contracts', 3, 5, 10, ARRAY['https://picsum.photos/seed/nft1/800/600', 'https://picsum.photos/seed/nft2/800/600', 'https://picsum.photos/seed/nft3/800/600', 'https://picsum.photos/seed/nft4/800/600'], ARRAY['$BLUR', '$LOOKS'], ARRAY['NFT', 'PFP', 'Collection', 'Generative Art'], '21-45 days', true),
('s3d008', 'b3d004', 'Custom NFT Artwork (1/1)', 'Hand-crafted unique NFT artwork perfect for high-value collections or special editions.', '3D & 2D Content Creation', 500, 1000, 2000, 7, 10, 14, '1 unique NFT artwork', '3 unique NFT artworks', '5 unique artworks with variations', 2, 4, 6, ARRAY['https://picsum.photos/seed/1of1-1/800/600', 'https://picsum.photos/seed/1of1-2/800/600'], ARRAY['$X2Y2'], ARRAY['NFT', '1/1', 'Art'], '7-14 days', false);

-- Services for KOL Builders
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('skol001', 'bkol001', 'Token Launch Promotion Package', 'Comprehensive token launch promotion across all my platforms. Guaranteed reach to 500K+ engaged crypto enthusiasts.', 'KOLs & Influencers', 5000, 10000, 20000, 3, 5, 7, '3 tweets, 1 TG post', '7 tweets, 3 TG posts, 1 IG story', '15 tweets, 5 TG posts, 3 IG posts, 1 Twitter Space', 1, 2, 3, ARRAY['partner:Blur', 'partner:Magic Eden', 'partner:Uniswap', 'partner:1inch'], ARRAY['$WIF', '$POPCAT', '$BONK'], ARRAY['Token Launch', 'Promotion', 'Marketing'], '3-7 days', true),
('skol002', 'bkol001', 'Community AMA Hosting', 'Host engaging AMA sessions for your project on Twitter Spaces or Discord. Professional moderation and question curation.', 'KOLs & Influencers', 2000, 3500, 6000, 2, 3, 5, '1-hour Twitter Space AMA', '2-hour AMA with pre-promotion', '3-hour AMA with recording, clips, and follow-up content', 0, 1, 2, ARRAY['partner:DexTools', 'partner:CoinGecko'], ARRAY['$MEW'], ARRAY['AMA', 'Community', 'Engagement'], '2-5 days', false),
('skol003', 'bkol002', 'Viral Tweet Campaign', 'Create and publish viral-optimized tweets that drive massive engagement. My tweets average 50K+ impressions.', 'KOLs & Influencers', 1500, 3000, 6000, 1, 2, 3, '5 viral tweets', '10 viral tweets with engagement boosting', '20 viral tweets with thread series and community raids', 2, 3, 5, ARRAY['partner:Tensor', 'partner:Raydium', 'partner:Jupiter'], ARRAY['$DEGEN', '$BRETT'], ARRAY['Viral Marketing', 'Twitter', 'Engagement'], '1-3 days', true),
('skol004', 'bkol002', 'Memecoin Launch Strategy', 'Complete memecoin launch strategy including content calendar, viral campaigns, and community building tactics.', 'KOLs & Influencers', 3000, 6000, 12000, 5, 7, 10, 'Content calendar (1 week)', 'Content + Campaign strategy (2 weeks)', 'Full launch strategy (4 weeks) with ongoing support', 2, 3, 5, ARRAY['partner:PumpFun', 'partner:DexScreener'], ARRAY['$MOG'], ARRAY['Memecoin', 'Launch', 'Strategy'], '5-10 days', true),
('skol005', 'bkol003', 'DeFi Project Coverage', 'In-depth coverage of your DeFi project including analysis threads, tutorial videos, and community education.', 'KOLs & Influencers', 2500, 5000, 9000, 5, 7, 10, '1 analysis thread, 1 tutorial', '3 threads, 2 tutorials, 1 review video', '5 threads, 4 tutorials, 3 videos, ongoing coverage', 2, 3, 4, ARRAY['partner:Aerodrome', 'partner:Synthetix'], ARRAY['$BASE', '$AERO'], ARRAY['DeFi', 'Coverage', 'Education'], '5-10 days', false),
('skol006', 'bkol004', 'Influencer Network Coordination', 'Coordinate campaigns across my network of 50+ crypto influencers for maximum reach and impact.', 'KOLs & Influencers', 8000, 15000, 30000, 7, 10, 14, '10 influencers, coordinated posts', '25 influencers, campaign strategy', '50+ influencers, full campaign management', 2, 3, 5, ARRAY['partner:PumpFun', 'partner:DexTools'], ARRAY['$PEPE', '$SHIB', '$FLOKI'], ARRAY['Influencer Network', 'Campaign', 'Marketing'], '7-14 days', true);

-- Services for Development Builders  
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('sdev001', 'bdev001', 'Smart Contract Development & Audit', 'Professional smart contract development with built-in security best practices and optional third-party audit coordination.', 'Script Development', 2500, 5000, 10000, 14, 21, 30, 'Custom smart contract, Basic tests', 'Advanced contract, Full test suite, Gas optimization', 'Complex contract system, Formal verification, Coordinated audit', 3, 5, 10, ARRAY['https://picsum.photos/seed/contract1/800/600'], ARRAY['$UNI', '$AAVE'], ARRAY['Smart Contracts', 'Solidity', 'Security'], '14-30 days', true),
('sdev002', 'bdev001', 'DeFi Protocol Development', 'Build your DeFi protocol from scratch including AMM, lending, staking, or custom mechanisms.', 'Script Development', 8000, 15000, 30000, 30, 45, 60, 'Core protocol contracts', 'Full protocol with frontend', 'Complete platform with advanced features and audit', 5, 8, 15, ARRAY['https://picsum.photos/seed/defi1/800/600', 'https://picsum.photos/seed/defi2/800/600'], ARRAY['$COMP'], ARRAY['DeFi', 'Protocol', 'Smart Contracts'], '30-60 days', true),
('sdev003', 'bdev002', 'Full-Stack DApp Development', 'Complete dApp development including smart contracts, responsive frontend, and backend APIs.', 'Script Development', 3500, 7000, 15000, 21, 30, 45, 'Basic dApp (frontend + 1 contract)', 'Advanced dApp (frontend + multiple contracts + backend)', 'Enterprise dApp with admin panel and analytics', 5, 8, 12, ARRAY['https://picsum.photos/seed/dapp1/800/600', 'https://picsum.photos/seed/dapp2/800/600'], ARRAY['$OP', '$ARB', '$BASE'], ARRAY['DApp', 'Web3', 'Full-Stack'], '21-45 days', true),
('sdev004', 'bdev002', 'NFT Marketplace Development', 'Build your own NFT marketplace with advanced features like auctions, offers, and royalties.', 'Script Development', 5000, 10000, 20000, 30, 45, 60, 'Basic marketplace (buy/sell)', 'Advanced marketplace (auctions, offers)', 'Full-featured marketplace with analytics and admin tools', 5, 8, 15, ARRAY['https://picsum.photos/seed/nftmkt1/800/600'], ARRAY['$BLUR'], ARRAY['NFT', 'Marketplace', 'Smart Contracts'], '30-60 days', false),
('sdev005', 'bdev003', 'ERC-20 Token Contract', 'Create your custom ERC-20 token with advanced features like anti-bot protection, tax mechanisms, and more.', 'Script Development', 800, 1500, 3000, 5, 7, 10, 'Standard ERC-20 token', 'Token with tax/reflection', 'Advanced token with anti-bot, presale, and liquidity locks', 3, 5, 8, ARRAY['https://picsum.photos/seed/token1/800/600'], ARRAY['$SAFEMOON', '$SHIB'], ARRAY['Token', 'ERC-20', 'Smart Contracts'], '5-10 days', true),
('sdev006', 'bdev003', 'Token Presale & Launch System', 'Complete token launch infrastructure including presale contract, liquidity management, and anti-snipe protection.', 'Script Development', 2000, 4000, 8000, 10, 14, 21, 'Basic presale contract', 'Advanced presale with vesting', 'Full launch system with anti-bot and auto-liquidity', 3, 5, 10, ARRAY['https://picsum.photos/seed/presale1/800/600'], ARRAY['$FLOKI'], ARRAY['Presale', 'Token Launch', 'Smart Contracts'], '10-21 days', true),
('sdev007', 'bdev004', 'Solana Program Development', 'Build high-performance Solana programs using Anchor framework for your DeFi or NFT project.', 'Script Development', 3000, 6000, 12000, 14, 21, 30, 'Basic Solana program', 'Advanced program with multiple instructions', 'Complex program with optimizations and security features', 4, 6, 10, ARRAY['https://picsum.photos/seed/solana1/800/600'], ARRAY['$JUP', '$JTO', '$BONK'], ARRAY['Solana', 'Rust', 'Anchor'], '14-30 days', false);

-- Services for Marketing Builders
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('smkt001', 'bmkt001', 'Token Launch Marketing Campaign', 'Comprehensive marketing campaign for your token launch including strategy, content, and community growth.', 'Marketing & Growth', 2500, 5000, 10000, 14, 21, 30, 'Marketing strategy, Social media plan', 'Full campaign with influencer outreach', 'Complete campaign with paid ads and analytics', 3, 5, 8, ARRAY['partner:Farcaster', 'partner:Warpcast', 'partner:DexScreener'], ARRAY['$DEGEN', '$BRETT'], ARRAY['Marketing', 'Token Launch', 'Growth'], '14-30 days', true),
('smkt002', 'bmkt001', 'Community Growth Package', 'Grow your community from 0 to 10K+ engaged members with proven strategies and organic tactics.', 'Marketing & Growth', 1500, 3000, 6000, 30, 45, 60, 'Basic growth strategy', 'Growth strategy with content calendar', 'Full growth campaign with engagement tactics', 3, 5, 8, ARRAY['partner:Discord', 'partner:Telegram'], ARRAY['$TOSHI'], ARRAY['Community', 'Growth', 'Engagement'], '30-60 days', false),
('smkt003', 'bmkt002', 'Memecoin Viral Marketing', 'Create viral marketing campaigns specifically designed for memecoins. Guaranteed to create buzz and FOMO.', 'Marketing & Growth', 2000, 4000, 8000, 7, 14, 21, 'Viral content strategy (1 week)', 'Full viral campaign (2 weeks)', 'Extended campaign (4 weeks) with community raids', 3, 5, 10, ARRAY['partner:PumpFun', 'partner:Twitter'], ARRAY['$PEPE', '$WIF', '$POPCAT'], ARRAY['Memecoin', 'Viral Marketing', 'Social Media'], '7-21 days', true),
('smkt004', 'bmkt003', 'Data-Driven Growth Strategy', 'Use analytics and data to optimize your marketing funnel and maximize ROI on every marketing dollar.', 'Marketing & Growth', 1800, 3500, 7000, 14, 21, 30, 'Analytics setup and audit', 'Full funnel optimization', 'Ongoing optimization with A/B testing', 2, 4, 8, ARRAY['partner:Google Analytics', 'partner:Mixpanel'], ARRAY['$BASE', '$AERO'], ARRAY['Analytics', 'Growth', 'Optimization'], '14-30 days', false);

-- Continue with more services...
-- Graphic Design Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('sgfx001', 'bgfx001', 'Complete Brand Identity Package', 'Full brand identity including logo, color palette, typography, and brand guidelines for your crypto project.', 'Graphic Design', 1200, 2500, 5000, 10, 14, 21, 'Logo + Color palette', 'Logo, Colors, Typography, Basic guidelines', 'Complete brand book with all marketing templates', 3, 5, 10, ARRAY['https://picsum.photos/seed/brand1/800/600', 'https://picsum.photos/seed/brand2/800/600'], ARRAY['$BLUR', '$LOOKS'], ARRAY['Branding', 'Logo Design', 'Brand Identity'], '10-21 days', true),
('sgfx002', 'bgfx001', 'Social Media Graphics Package', 'Custom social media graphics for Twitter, Discord, Telegram, and more. Stand out in the crowded crypto space.', 'Graphic Design', 400, 800, 1500, 5, 7, 10, '10 social graphics', '25 social graphics + templates', '50+ graphics, Templates, Ongoing support', 2, 4, 6, ARRAY['https://picsum.photos/seed/social1/800/600'], ARRAY['$OPENSEA'], ARRAY['Social Media', 'Graphics', 'Marketing'], '5-10 days', false),
('sgfx003', 'bgfx002', 'DApp UI/UX Design', 'Beautiful, intuitive user interfaces for your DeFi protocol or NFT platform. User-tested and conversion-optimized.', 'Graphic Design', 2000, 4000, 8000, 14, 21, 30, 'UI design for 5 screens', 'Full UI/UX for 15 screens', 'Complete design system with prototypes', 4, 6, 10, ARRAY['https://picsum.photos/seed/ui1/800/600', 'https://picsum.photos/seed/ui2/800/600'], ARRAY['$UNI', '$AAVE'], ARRAY['UI/UX', 'DApp', 'Design'], '14-30 days', true),
('sgfx004', 'bgfx003', 'Animated Logo & Branding', 'Bring your brand to life with animated logos and motion branding perfect for videos and social media.', 'Graphic Design', 600, 1200, 2400, 7, 10, 14, 'Animated logo (10s)', 'Logo + Brand animation package', 'Full animated brand suite with variations', 3, 5, 8, ARRAY['https://picsum.photos/seed/animlogo1/800/600'], ARRAY['$DEGEN', '$BRETT'], ARRAY['Animation', 'Logo', 'Branding'], '7-14 days', true);

-- Video Editing Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('svid001', 'bvid001', 'Token Launch Video Production', 'Professional launch videos that explain your project and drive conversions. Perfect for social media and pitches.', 'Video Editing', 800, 1500, 3000, 7, 10, 14, '60-second launch video', '90-second video with custom graphics', '2-minute cinematic video with voiceover', 3, 5, 8, ARRAY['https://picsum.photos/seed/video1/800/600'], ARRAY['$PRIME', '$GALA'], ARRAY['Video Production', 'Launch', 'Marketing'], '7-14 days', true),
('svid002', 'bvid001', 'Tutorial & Explainer Videos', 'Create engaging tutorial videos that educate users about your protocol or product in an easy-to-understand way.', 'Video Editing', 600, 1200, 2400, 5, 7, 10, '1 tutorial video (2-3 min)', '3 tutorial videos', '5+ tutorial videos with graphics package', 2, 4, 6, ARRAY['https://picsum.photos/seed/tutorial1/800/600'], ARRAY['$UNI'], ARRAY['Tutorial', 'Education', 'Video'], '5-10 days', false),
('svid003', 'bvid002', 'Cinematic Project Showcase', 'High-end cinematic videos that showcase your project in the best light. Perfect for pitches and investor presentations.', 'Video Editing', 1500, 3000, 6000, 10, 14, 21, '2-minute showcase video', '3-minute video with interviews', '5-minute documentary-style showcase', 3, 5, 8, ARRAY['https://picsum.photos/seed/cinema1/800/600'], ARRAY['$APE', '$AZUKI'], ARRAY['Cinematic', 'Showcase', 'Professional'], '10-21 days', true),
('svid004', 'bvid003', 'Viral Short-Form Content', 'Create viral TikToks, Reels, and Shorts that drive massive engagement for your crypto project.', 'Video Editing', 300, 600, 1200, 3, 5, 7, '5 short-form videos', '15 short-form videos', '30 short-form videos with trending audio', 2, 3, 5, ARRAY['https://picsum.photos/seed/short1/800/600'], ARRAY['$PEPE', '$WIF', '$DOGE'], ARRAY['Short-Form', 'Viral', 'Social Media'], '3-7 days', true);

-- Social Media Management Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('ssoc001', 'bsoc001', 'Full Social Media Management', 'Complete social media management across all platforms. Daily posts, engagement, and community interaction.', 'Social Media Management', 1500, 3000, 6000, 30, 30, 30, '3 posts/week, Basic engagement', '7 posts/week, Full engagement', 'Daily posts, Stories, Full community management', 0, 0, 0, ARRAY['partner:Twitter', 'partner:Instagram', 'partner:Facebook'], ARRAY['$BASE', '$DEGEN'], ARRAY['Social Media', 'Management', 'Community'], 'Monthly', true),
('ssoc002', 'bsoc001', 'Content Creation Package', 'Custom content creation including graphics, captions, and hashtag strategy for your crypto project.', 'Social Media Management', 800, 1500, 3000, 7, 14, 30, '20 posts/month', '40 posts/month with scheduling', '60+ posts/month with full strategy', 2, 3, 5, ARRAY['partner:Canva', 'partner:Later'], ARRAY['$BRETT'], ARRAY['Content Creation', 'Social Media'], '7-30 days', false),
('ssoc003', 'bsoc002', 'Community Engagement Service', 'Daily community engagement to build relationships and grow your follower base organically.', 'Social Media Management', 600, 1200, 2400, 30, 30, 30, '1 hour/day engagement', '2 hours/day engagement', '4+ hours/day full community support', 0, 0, 0, ARRAY['partner:Discord', 'partner:Telegram'], ARRAY['$TOSHI'], ARRAY['Engagement', 'Community', 'Growth'], 'Monthly', false);

-- Mods & Raiders Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('smod001', 'bmod001', 'Discord Community Moderation', '24/7 professional Discord moderation service. Keep your community safe, engaged, and growing.', 'Mods & Raiders', 800, 1500, 3000, 30, 30, 30, 'Basic moderation (8hrs/day)', 'Standard moderation (16hrs/day)', 'Premium 24/7 coverage with multiple mods', 0, 0, 0, ARRAY['partner:Discord', 'partner:MEE6'], ARRAY['$DEGEN', '$BRETT'], ARRAY['Moderation', 'Discord', 'Community'], 'Monthly', true),
('smod002', 'bmod001', 'Event Hosting & Management', 'Host engaging community events like AMAs, contests, and gaming nights to boost engagement.', 'Mods & Raiders', 400, 800, 1500, 7, 7, 7, '2 events/month', '4 events/month', '8 events/month with full production', 1, 2, 3, ARRAY['partner:Discord', 'partner:Twitter'], ARRAY['$TOSHI'], ARRAY['Events', 'Community', 'Engagement'], 'Weekly', false),
('smod003', 'bmod002', 'Community Raid Coordination', 'Organize strategic community raids to boost engagement and visibility for your project.', 'Mods & Raiders', 500, 1000, 2000, 7, 14, 30, '4 raids/month', '8 raids/month', '15+ raids/month with full strategy', 1, 2, 3, ARRAY['partner:Twitter', 'partner:Discord'], ARRAY['$PEPE', '$WIF'], ARRAY['Raids', 'Engagement', 'Growth'], '7-30 days', true);

-- Volume Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('svol001', 'bvol001', 'Token Volume Generation', 'Organic-looking volume generation for your token launch. Prevent low volume death and maintain healthy charts.', 'Volume Services', 2000, 5000, 10000, 7, 14, 30, '$50K trading volume', '$250K trading volume', '$1M+ trading volume with sustained activity', 1, 2, 3, ARRAY['partner:Uniswap', 'partner:DexScreener'], ARRAY['$UNI', '$SUSHI'], ARRAY['Volume', 'Market Making', 'Trading'], '7-30 days', true),
('svol002', 'bvol001', 'Liquidity Provision Service', 'Professional liquidity provision to ensure smooth trading and prevent slippage for your token.', 'Volume Services', 1500, 3000, 6000, 7, 14, 30, 'Basic LP provision', 'Advanced LP with rebalancing', 'Full market making service', 1, 2, 3, ARRAY['partner:PancakeSwap'], ARRAY['$CAKE'], ARRAY['Liquidity', 'Market Making'], '7-30 days', false),
('svol003', 'bvol002', 'Launch Volume Support', 'Ensure your token launch has healthy volume from day one. Prevent snipers and maintain fair distribution.', 'Volume Services', 3000, 6000, 12000, 3, 5, 7, '24-hour launch support', '3-day launch support', '7-day launch support with anti-bot', 1, 2, 3, ARRAY['partner:Aerodrome'], ARRAY['$AERO', '$VELODROME'], ARRAY['Launch', 'Volume', 'Anti-Bot'], '3-7 days', true);

-- Strategy Consulting Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('sstr001', 'bstr001', 'Web3 Project Strategy Consultation', 'Comprehensive strategic consultation covering all aspects of your Web3 project from tokenomics to go-to-market.', 'Strategy Consulting', 1500, 3000, 6000, 7, 14, 21, '2-hour consultation + report', '4 hours + Detailed strategy doc', '8+ hours + Full strategic plan', 2, 3, 5, ARRAY['partner:Notion', 'partner:Figma'], ARRAY['$UNI', '$AAVE'], ARRAY['Strategy', 'Consulting', 'Planning'], '7-21 days', true),
('sstr002', 'bstr001', 'Go-to-Market Strategy', 'Detailed go-to-market strategy to successfully launch and scale your crypto project.', 'Strategy Consulting', 2000, 4000, 8000, 10, 14, 21, 'Basic GTM plan', 'Detailed GTM with tactics', 'Complete GTM playbook with execution support', 2, 3, 5, ARRAY['partner:Miro'], ARRAY['$COMP'], ARRAY['Go-to-Market', 'Strategy', 'Launch'], '10-21 days', false),
('sstr003', 'bstr002', 'Tokenomics Design & Modeling', 'Professional tokenomics design with economic modeling to ensure long-term sustainability and value accrual.', 'Strategy Consulting', 2500, 5000, 10000, 14, 21, 30, 'Basic tokenomics model', 'Advanced model with simulations', 'Complete tokenomics with whitepaper section', 3, 5, 8, ARRAY['partner:Excel', 'partner:Jupyter'], ARRAY['$CURVE', '$CVX'], ARRAY['Tokenomics', 'Economics', 'Modeling'], '14-30 days', true);

-- Documentation Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('sdoc001', 'bdoc001', 'Whitepaper Writing', 'Professional whitepaper writing that clearly communicates your project vision, technology, and value proposition.', 'Documentation & Paperwork', 1500, 3000, 6000, 14, 21, 30, 'Basic whitepaper (10-15 pages)', 'Advanced whitepaper (20-30 pages)', 'Comprehensive whitepaper (40+ pages) with technical details', 3, 5, 10, ARRAY['partner:Google Docs', 'partner:LaTeX'], ARRAY['$ETH', '$BTC'], ARRAY['Whitepaper', 'Documentation', 'Writing'], '14-30 days', true),
('sdoc002', 'bdoc001', 'Technical Documentation', 'Clear, comprehensive technical documentation for your smart contracts, APIs, and developer tools.', 'Documentation & Paperwork', 800, 1500, 3000, 7, 14, 21, 'Basic API docs', 'Full technical documentation', 'Complete developer portal with examples', 2, 4, 6, ARRAY['partner:GitBook', 'partner:ReadTheDocs'], ARRAY['$LINK'], ARRAY['Technical Docs', 'API', 'Development'], '7-21 days', false),
('sdoc003', 'bdoc002', 'Legal Compliance Package', 'Ensure your project meets all legal requirements with comprehensive compliance documentation and analysis.', 'Documentation & Paperwork', 2000, 4000, 8000, 14, 21, 30, 'Basic compliance review', 'Full compliance package with ToS', 'Complete legal package with multiple jurisdictions', 2, 3, 5, ARRAY['partner:DocuSign'], ARRAY['$USDC', '$USDT'], ARRAY['Legal', 'Compliance', 'Documentation'], '14-30 days', true);

-- Grants & Funding Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, is_featured) VALUES
('sgrn001', 'bgrn001', 'Grant Application Writing', 'Professional grant application writing with proven track record of success across major ecosystems.', 'Grants & Funding', 1000, 2000, 4000, 14, 21, 30, '1 grant application', '3 grant applications', '5+ applications with ongoing support', 2, 3, 5, ARRAY['partner:Notion'], ARRAY['$OP', '$ARB', '$BASE'], ARRAY['Grants', 'Funding', 'Writing'], '14-30 days', true),
('sgrn002', 'bgrn001', 'Ecosystem Fund Strategy', 'Strategic guidance on which ecosystem funds to apply for and how to maximize your chances of success.', 'Grants & Funding', 800, 1500, 3000, 7, 14, 21, '1-hour consultation + roadmap', 'Full ecosystem analysis + applications', 'Complete funding strategy with execution', 2, 3, 5, ARRAY['partner:Airtable'], ARRAY['$MATIC'], ARRAY['Ecosystem', 'Funding', 'Strategy'], '7-21 days', false),
('sgrn003', 'bgrn002', 'VC Pitch Deck Creation', 'Create compelling pitch decks that help you raise funds from VCs and angel investors.', 'Grants & Funding', 1200, 2500, 5000, 10, 14, 21, 'Basic pitch deck (10 slides)', 'Professional deck (15 slides)', 'Complete pitch package with financials', 3, 5, 8, ARRAY['partner:Figma', 'partner:Canva'], ARRAY['$AVAX'], ARRAY['Pitch Deck', 'VC', 'Fundraising'], '10-21 days', true);
