-- Services for 3D & 2D Content Builders
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, psx_required, featured) VALUES
('s3d001', 'b3d001', 'Hyper-Realistic 3D Character Design', 'Create stunning 3D characters for your Web3 game or NFT project. Includes high-poly modeling, texturing, rigging, and basic animations.', '3D & 2D Content Creation', 450, 850, 1500, 7, 10, 14, 'High-poly 3D model, Basic textures, T-pose', 'Fully textured model, Advanced rigging, 3 animations', 'Game-ready model, Full animation set, Multiple LODs, Source files', ARRAY['High-poly 3D model', 'Basic textures', 'T-pose'], ARRAY['Fully textured model', 'Advanced rigging', '3 animations'], ARRAY['Game-ready model', 'Full animation set', 'Multiple LODs', 'Source files'], 2, 4, 6, ARRAY['https://picsum.photos/seed/3dchar1/800/600', 'https://picsum.photos/seed/3dchar2/800/600', 'https://picsum.photos/seed/3dchar3/800/600'], ARRAY['$PRIME', '$GALA', '$BEAM'], ARRAY['3D Modeling', 'Character Design', 'Game Assets', 'NFT'], '7-14 days', 0, true),
('s3d002', 'b3d001', '3D Weapon & Item Design', 'Design unique weapons and items for your game or metaverse project. High-quality assets optimized for real-time rendering.', '3D & 2D Content Creation', 300, 600, 1000, 5, 7, 10, '1 weapon/item model', '3 weapon/item models with variations', '5+ models, Multiple materials, Particle effects', ARRAY['1 weapon/item model'], ARRAY['3 weapon/item models with variations'], ARRAY['5+ models', 'Multiple materials', 'Particle effects'], 2, 3, 5, ARRAY['https://picsum.photos/seed/weapon1/800/600', 'https://picsum.photos/seed/weapon2/800/600'], ARRAY['$PRIME', '$RONIN'], ARRAY['3D Modeling', 'Game Assets', 'Weapons', 'Items'], '5-10 days', 0, false),
('s3d003', 'b3d002', 'Cinematic 3D Environment Design', 'Breathtaking 3D environments for marketing renders, trailers, or game levels. Perfect for token launches and NFT showcases.', '3D & 2D Content Creation', 600, 1200, 2200, 10, 14, 21, 'Basic environment scene, 2 render angles', 'Detailed environment, 5 render angles, Lighting setup', 'Highly detailed scene, Unlimited angles, Animation, Source files', ARRAY['Basic environment scene', '2 render angles'], ARRAY['Detailed environment', '5 render angles', 'Lighting setup'], ARRAY['Highly detailed scene', 'Unlimited angles', 'Animation', 'Source files'], 2, 3, 5, ARRAY['https://picsum.photos/seed/env1/800/600', 'https://picsum.photos/seed/env2/800/600', 'https://picsum.photos/seed/env3/800/600'], ARRAY['$APE', '$DEGEN'], ARRAY['3D Environments', 'Rendering', 'Marketing'], '10-21 days', 0, true);

-- Continue with a smaller set to test
-- KOL Services (just a few for testing)
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, psx_required, featured) VALUES
('skol001', 'bkol001', 'Token Launch Promotion Package', 'Comprehensive token launch promotion across all my platforms. Guaranteed reach to 500K+ engaged crypto enthusiasts.', 'KOLs & Influencers', 5000, 10000, 20000, 3, 5, 7, '3 tweets, 1 TG post', '7 tweets, 3 TG posts, 1 IG story', '15 tweets, 5 TG posts, 3 IG posts, 1 Twitter Space', ARRAY['3 tweets', '1 TG post'], ARRAY['7 tweets', '3 TG posts', '1 IG story'], ARRAY['15 tweets', '5 TG posts', '3 IG posts', '1 Twitter Space'], 1, 2, 3, ARRAY['partner:Blur', 'partner:Magic Eden', 'partner:Uniswap', 'partner:1inch'], ARRAY['$WIF', '$POPCAT', '$BONK'], ARRAY['Token Launch', 'Promotion', 'Marketing'], '3-7 days', 0, true),
('skol002', 'bkol002', 'Viral Tweet Campaign', 'Create and publish viral-optimized tweets that drive massive engagement. My tweets average 50K+ impressions.', 'KOLs & Influencers', 1500, 3000, 6000, 1, 2, 3, '5 viral tweets', '10 viral tweets with engagement boosting', '20 viral tweets with thread series and community raids', ARRAY['5 viral tweets'], ARRAY['10 viral tweets', 'Engagement boosting'], ARRAY['20 viral tweets', 'Thread series', 'Community raids'], 2, 3, 5, ARRAY['partner:Tensor', 'partner:Raydium', 'partner:Jupiter'], ARRAY['$DEGEN', '$BRETT'], ARRAY['Viral Marketing', 'Twitter', 'Engagement'], '1-3 days', 0, true);

-- Dev Services
INSERT INTO services (id, builder_id, title, description, category, basic_price, standard_price, premium_price, basic_delivery_days, standard_delivery_days, premium_delivery_days, basic_description, standard_description, premium_description, basic_deliverables, standard_deliverables, premium_deliverables, basic_revisions, standard_revisions, premium_revisions, portfolio_media, token_tickers, tags, delivery_time, psx_required, featured) VALUES
('sdev001', 'bdev001', 'Smart Contract Development & Audit', 'Professional smart contract development with built-in security best practices and optional third-party audit coordination.', 'Script Development', 2500, 5000, 10000, 14, 21, 30, 'Custom smart contract, Basic tests', 'Advanced contract, Full test suite, Gas optimization', 'Complex contract system, Formal verification, Coordinated audit', ARRAY['Custom smart contract', 'Basic tests'], ARRAY['Advanced contract', 'Full test suite', 'Gas optimization'], ARRAY['Complex contract system', 'Formal verification', 'Coordinated audit'], 3, 5, 10, ARRAY['https://picsum.photos/seed/contract1/800/600'], ARRAY['$UNI', '$AAVE'], ARRAY['Smart Contracts', 'Solidity', 'Security'], '14-30 days', 0, true),
('sdev002', 'bdev002', 'Full-Stack DApp Development', 'Complete dApp development including smart contracts, responsive frontend, and backend APIs.', 'Script Development', 3500, 7000, 15000, 21, 30, 45, 'Basic dApp (frontend + 1 contract)', 'Advanced dApp (frontend + multiple contracts + backend)', 'Enterprise dApp with admin panel and analytics', ARRAY['Basic dApp', 'Frontend', '1 contract'], ARRAY['Advanced dApp', 'Frontend', 'Multiple contracts', 'Backend'], ARRAY['Enterprise dApp', 'Admin panel', 'Analytics'], 5, 8, 12, ARRAY['https://picsum.photos/seed/dapp1/800/600', 'https://picsum.photos/seed/dapp2/800/600'], ARRAY['$OP', '$ARB', '$BASE'], ARRAY['DApp', 'Web3', 'Full-Stack'], '21-45 days', 0, true),
('sdev003', 'bdev003', 'ERC-20 Token Contract', 'Create your custom ERC-20 token with advanced features like anti-bot protection, tax mechanisms, and more.', 'Script Development', 800, 1500, 3000, 5, 7, 10, 'Standard ERC-20 token', 'Token with tax/reflection', 'Advanced token with anti-bot, presale, and liquidity locks', ARRAY['Standard ERC-20 token'], ARRAY['Token with tax/reflection'], ARRAY['Advanced token with anti-bot', 'Presale', 'Liquidity locks'], 3, 5, 8, ARRAY['https://picsum.photos/seed/token1/800/600'], ARRAY['$SAFEMOON', '$SHIB'], ARRAY['Token', 'ERC-20', 'Smart Contracts'], '5-10 days', 0, true);
