import { db } from "./db";
import { builders, services } from "@shared/schema";

// Import generated images
const profileImages = {
  artist3d: '/attached_assets/generated_images/3D_Artist_Professional_Headshot_9d51c38f.png',
  developer: '/attached_assets/generated_images/Blockchain_Developer_Professional_Headshot_6944dea4.png',
  marketer: '/attached_assets/generated_images/Marketing_KOL_Professional_Headshot_06788695.png',
  designer: '/attached_assets/generated_images/Graphic_Designer_Professional_Headshot_423504f0.png',
  videoEditor: '/attached_assets/generated_images/Video_Editor_Professional_Headshot_4d6a7d17.png',
};

const serviceImages = {
  nft3d: '/attached_assets/generated_images/3D_NFT_Character_Render_a0707d39.png',
  logo: '/attached_assets/generated_images/Crypto_Logo_Design_e5140a88.png',
  video: '/attached_assets/generated_images/Video_Editing_Showcase_b32aef47.png',
  socialMedia: '/attached_assets/generated_images/Social_Media_Marketing_Graphics_b5a249f0.png',
  whitepaper: '/attached_assets/generated_images/Blockchain_Whitepaper_Design_9f0ac7ce.png',
};

const sampleBuilders = [
  {
    walletAddress: "0x1234567890123456789012345678901234567890",
    email: "alex.chen@web3talent.com",
    name: "Alex Chen",
    headline: "Award-Winning 3D Artist & NFT Creator",
    bio: "I specialize in creating stunning 3D characters and environments for NFT projects. With over 5 years of experience in the Web3 space, I've worked with top-tier projects including Pudgy Penguins, Doodles, and several successful memecoin launches. My work focuses on creating unique, memorable characters that drive community engagement.",
    profileImage: profileImages.artist3d,
    verified: true,
    category: "3D Content Creation",
    rating: "4.95",
    reviewCount: 127,
    completedProjects: 143,
    responseTime: "1 hour",
    twitterHandle: "@alex3dart",
    twitterFollowers: 45000,
    discordHandle: "alex3d#1234",
    portfolioLinks: ["https://artstation.com/alexchen", "https://foundation.app/alex3d"],
    skills: ["Blender", "Cinema 4D", "ZBrush", "Substance Painter", "Unreal Engine", "NFT Art"],
    tokenTickers: ["$CREATE", "$PSX"],
    psxTier: "platinum",
    portfolioMedia: [serviceImages.nft3d, serviceImages.nft3d],
    software3D: ["Blender", "Cinema 4D", "ZBrush", "Substance Painter"],
    renderEngines: ["Cycles", "Octane", "Redshift"],
    styleSpecialties: ["Cyberpunk", "Cute Characters", "Sci-Fi", "Fantasy"],
    animationExpertise: true,
    acceptingOrders: true,
    isActive: true,
    isLive: true,
    languages: ["English", "Mandarin"],
    timezone: "Asia/Singapore",
    country: "Singapore",
    city: "Singapore",
    yearsOfExperience: 5,
    availability: "available",
    hoursPerWeek: 40,
    description: "Passionate 3D artist with a deep love for Web3 and NFTs. I bring your vision to life with meticulous attention to detail and creative flair.",
    hourlyRate: "150.00",
    minProjectBudget: "500.00",
    maxProjectBudget: "5000.00",
    verificationBadges: ["Top Rated", "Verified Pro", "Fast Response"],
    badges: ["Rising Talent", "Top Seller", "Level 2"],
    lastActiveAt: new Date().toISOString(),
  },
  {
    walletAddress: "0x2345678901234567890123456789012345678901",
    email: "maya.johnson@blockchain.dev",
    name: "Maya Johnson",
    headline: "Senior Blockchain Developer | Smart Contract Specialist",
    bio: "Full-stack blockchain developer with expertise in Solidity, Rust, and Web3 integrations. I've built and audited smart contracts for DeFi protocols, NFT marketplaces, and DAO governance systems. My focus is on writing secure, gas-optimized code that passes rigorous audits.",
    profileImage: profileImages.developer,
    verified: true,
    category: "Script Development",
    rating: "4.98",
    reviewCount: 89,
    completedProjects: 96,
    responseTime: "2 hours",
    twitterHandle: "@mayablockchain",
    twitterFollowers: 28000,
    githubProfile: "github.com/mayajohnson",
    portfolioLinks: ["https://github.com/mayajohnson", "https://etherscan.io/address/0x..."],
    skills: ["Solidity", "Rust", "Hardhat", "Foundry", "Web3.js", "Ethers.js", "React"],
    tokenTickers: ["$CREATE"],
    psxTier: "gold",
    programmingLanguages: ["Solidity", "Rust", "TypeScript", "JavaScript", "Python"],
    blockchainFrameworks: ["Hardhat", "Foundry", "Truffle", "Anchor"],
    deployedContracts: ["ERC-721", "ERC-1155", "ERC-20", "DAO Governance"],
    auditReports: ["OpenZeppelin", "Trail of Bits"],
    certifications: ["Certified Blockchain Developer", "Solidity Expert"],
    acceptingOrders: true,
    isActive: true,
    isLive: true,
    languages: ["English", "Spanish"],
    timezone: "America/New_York",
    country: "United States",
    city: "New York",
    yearsOfExperience: 6,
    availability: "available",
    hoursPerWeek: 35,
    description: "Building the future of Web3, one smart contract at a time. Security and efficiency are my top priorities.",
    hourlyRate: "200.00",
    minProjectBudget: "1000.00",
    maxProjectBudget: "10000.00",
    verificationBadges: ["Verified Pro", "Security Expert", "Top Rated"],
    badges: ["Expert Seller", "Level 3", "Fast Delivery"],
    lastActiveAt: new Date().toISOString(),
  },
  {
    walletAddress: "0x3456789012345678901234567890123456789012",
    email: "carlos.rivera@web3marketing.com",
    name: "Carlos Rivera",
    headline: "Web3 Marketing Expert | KOL with 200K+ Followers",
    bio: "I help crypto projects achieve massive growth through strategic marketing campaigns. With a combined following of 200K+ across Twitter, Instagram, and TikTok, I specialize in memecoin launches, NFT marketing, and community building. My campaigns have generated millions in volume and built thriving communities.",
    profileImage: profileImages.marketer,
    verified: true,
    category: "KOLs & Influencers",
    rating: "4.92",
    reviewCount: 156,
    completedProjects: 189,
    responseTime: "30 minutes",
    twitterHandle: "@carlosweb3",
    twitterFollowers: 120000,
    instagramHandle: "@carlosweb3",
    instagramFollowers: 65000,
    telegramHandle: "@carlosrivera",
    telegramMembers: 15000,
    portfolioLinks: ["https://twitter.com/carlosweb3", "https://instagram.com/carlosweb3"],
    skills: ["Twitter Marketing", "Community Management", "Influencer Outreach", "Content Strategy", "KOL Coordination"],
    tokenTickers: ["$PSX", "$CREATE"],
    psxTier: "platinum",
    engagementRate: "8.50",
    audienceDemographics: "80% crypto natives, 20% traditional investors, primarily 18-35 age range",
    contentNiches: ["Crypto", "NFTs", "DeFi", "Memecoins", "Web3 Gaming"],
    brandPartnerships: ["Binance", "Coinbase", "OpenSea", "Magic Eden"],
    marketingPlatforms: ["Twitter", "Instagram", "TikTok", "Telegram", "Discord"],
    growthStrategies: ["Viral Content", "Influencer Collaborations", "Community Contests", "AMA Sessions"],
    acceptingOrders: true,
    isActive: true,
    isLive: true,
    languages: ["English", "Spanish", "Portuguese"],
    timezone: "America/Los_Angeles",
    country: "United States",
    city: "Los Angeles",
    yearsOfExperience: 4,
    availability: "available",
    hoursPerWeek: 50,
    description: "Turning crypto projects into viral sensations. Let's build your community together!",
    hourlyRate: "180.00",
    minProjectBudget: "800.00",
    maxProjectBudget: "8000.00",
    verificationBadges: ["Verified KOL", "Top Influencer", "Fast Response"],
    badges: ["Top Seller", "Marketing Pro", "Level 3"],
    lastActiveAt: new Date().toISOString(),
  },
  {
    walletAddress: "0x4567890123456789012345678901234567890123",
    email: "sophia.martinez@designstudio.xyz",
    name: "Sophia Martinez",
    headline: "Creative Graphic Designer | Web3 Branding Specialist",
    bio: "I create stunning visual identities for Web3 projects. From logos and brand guidelines to social media graphics and marketing materials, I deliver cohesive, professional designs that resonate with crypto-native audiences. My portfolio includes work for successful NFT projects, DeFi protocols, and memecoin launches.",
    profileImage: profileImages.designer,
    verified: true,
    category: "Graphic Design",
    rating: "4.96",
    reviewCount: 201,
    completedProjects: 234,
    responseTime: "1 hour",
    twitterHandle: "@sophiadesigns",
    twitterFollowers: 32000,
    portfolioLinks: ["https://behance.net/sophiamartinez", "https://dribbble.com/sophiadesigns"],
    skills: ["Logo Design", "Brand Identity", "Social Media Graphics", "Web Design", "Illustration", "Typography"],
    tokenTickers: ["$CREATE"],
    psxTier: "gold",
    portfolioMedia: [serviceImages.logo, serviceImages.socialMedia],
    acceptingOrders: true,
    isActive: true,
    isLive: true,
    languages: ["English", "Spanish"],
    timezone: "America/Chicago",
    country: "United States",
    city: "Chicago",
    yearsOfExperience: 7,
    availability: "available",
    hoursPerWeek: 40,
    description: "Crafting beautiful brands that stand out in the crowded Web3 space. Let's make your project unforgettable!",
    hourlyRate: "120.00",
    minProjectBudget: "300.00",
    maxProjectBudget: "3000.00",
    verificationBadges: ["Verified Pro", "Design Expert", "Top Rated"],
    badges: ["Rising Star", "Level 2", "Fast Delivery"],
    lastActiveAt: new Date().toISOString(),
  },
  {
    walletAddress: "0x5678901234567890123456789012345678901234",
    email: "david.kim@videoproduction.web3",
    name: "David Kim",
    headline: "Professional Video Editor | Crypto Content Specialist",
    bio: "I produce high-quality promotional videos, explainer content, and social media clips for Web3 projects. My work has been featured in campaigns that generated millions of views and significant community engagement. I specialize in fast-paced, attention-grabbing content optimized for Twitter, YouTube, and TikTok.",
    profileImage: profileImages.videoEditor,
    verified: true,
    category: "Video Editing",
    rating: "4.94",
    reviewCount: 112,
    completedProjects: 128,
    responseTime: "2 hours",
    twitterHandle: "@davidvideoweb3",
    twitterFollowers: 18000,
    youtubeChannel: "youtube.com/@davidkim",
    youtubeSubscribers: 25000,
    portfolioLinks: ["https://youtube.com/@davidkim", "https://vimeo.com/davidkim"],
    skills: ["Video Editing", "Motion Graphics", "Color Grading", "Sound Design", "3D Animation"],
    tokenTickers: ["$PSX"],
    psxTier: "silver",
    portfolioMedia: [serviceImages.video],
    editingSoftware: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve", "Final Cut Pro"],
    editingSpecialties: ["Promotional Videos", "Explainers", "Social Media Content", "Cinematic Trailers"],
    videoTypes: ["Promotional", "Educational", "Social Ads", "Product Demos"],
    avgTurnaroundDays: 3,
    portfolioReel: serviceImages.video,
    acceptingOrders: true,
    isActive: true,
    isLive: false,
    languages: ["English", "Korean"],
    timezone: "America/Los_Angeles",
    country: "South Korea",
    city: "Seoul",
    yearsOfExperience: 5,
    availability: "available",
    hoursPerWeek: 35,
    description: "Creating scroll-stopping video content that converts viewers into believers. Let's tell your story!",
    hourlyRate: "140.00",
    minProjectBudget: "400.00",
    maxProjectBudget: "4000.00",
    verificationBadges: ["Verified Pro", "Video Expert"],
    badges: ["Content Creator", "Level 2"],
    lastActiveAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

const sampleServices = [
  {
    builderId: null, // Will be set after builders are created
    title: "Professional 3D NFT Character Design",
    description: "Get a unique, high-quality 3D character designed specifically for your NFT collection. Includes full rigging, texturing, and multiple render passes for maximum flexibility.",
    category: "3D Content Creation",
    deliveryTime: "5 days",
    basicPrice: "800.00",
    standardPrice: "1500.00",
    premiumPrice: "2500.00",
    basicDescription: "Single 3D character with basic textures and 1 render angle",
    standardDescription: "Fully rigged character with advanced textures and 3 render angles",
    premiumDescription: "Premium character with animation-ready rig, 4K textures, and 5+ render angles",
    basicDeliverables: ["3D model file", "1 rendered image (4K)", "Source files"],
    standardDeliverables: ["Rigged 3D model", "3 rendered images (4K)", "Texture maps", "Source files"],
    premiumDeliverables: ["Animation-ready rig", "5+ rendered images (4K)", "4K texture maps", "All source files", "Turnaround sheet"],
    basicDeliveryDays: 7,
    standardDeliveryDays: 5,
    premiumDeliveryDays: 3,
    basicRevisions: 2,
    standardRevisions: 3,
    premiumRevisions: 5,
    tags: ["3D", "NFT", "Character Design", "Blender", "High Quality"],
    tokenTickers: ["$CREATE", "$PSX"],
    psxRequired: "100.00",
    featured: true,
    portfolioMedia: [serviceImages.nft3d],
    active: true,
  },
  {
    builderId: null,
    title: "Smart Contract Development & Audit",
    description: "Professional smart contract development with security audit included. I write secure, gas-optimized contracts for ERC-20, ERC-721, ERC-1155, and custom protocols.",
    category: "Script Development",
    deliveryTime: "7 days",
    basicPrice: "1200.00",
    standardPrice: "2500.00",
    premiumPrice: "5000.00",
    basicDescription: "Simple ERC-20 or ERC-721 contract with basic features",
    standardDescription: "Advanced contract with custom features and internal audit",
    premiumDescription: "Complex protocol with multiple contracts, full audit, and deployment support",
    basicDeliverables: ["Smart contract code", "Basic tests", "Deployment script"],
    standardDeliverables: ["Advanced contract code", "Comprehensive tests", "Internal audit report", "Deployment & verification"],
    premiumDeliverables: ["Multi-contract system", "Full test coverage", "Professional audit report", "Gas optimization", "Deployment support", "Documentation"],
    basicDeliveryDays: 10,
    standardDeliveryDays: 7,
    premiumDeliveryDays: 5,
    basicRevisions: 1,
    standardRevisions: 2,
    premiumRevisions: 3,
    tags: ["Solidity", "Smart Contracts", "Security", "Audit", "Blockchain"],
    tokenTickers: ["$CREATE"],
    psxRequired: "150.00",
    featured: true,
    active: true,
  },
  {
    builderId: null,
    title: "Viral Twitter Marketing Campaign",
    description: "Comprehensive Twitter marketing campaign designed to maximize reach and engagement. Includes content strategy, influencer coordination, and community management.",
    category: "KOLs & Influencers",
    deliveryTime: "3 days",
    basicPrice: "500.00",
    standardPrice: "1200.00",
    premiumPrice: "2500.00",
    basicDescription: "3 promotional tweets from my account (120K followers)",
    standardDescription: "7-day campaign with daily tweets, influencer outreach, and engagement tracking",
    premiumDescription: "14-day comprehensive campaign with KOL coordination, viral content strategy, and detailed analytics",
    basicDeliverables: ["3 promotional tweets", "Basic analytics"],
    standardDeliverables: ["Daily tweets (7 days)", "Influencer outreach (5 KOLs)", "Engagement tracking", "Weekly report"],
    premiumDeliverables: ["Daily tweets (14 days)", "KOL coordination (10+ influencers)", "Viral content strategy", "Community contests", "Detailed analytics", "Growth report"],
    basicDeliveryDays: 3,
    standardDeliveryDays: 7,
    premiumDeliveryDays: 14,
    basicRevisions: 1,
    standardRevisions: 2,
    premiumRevisions: 3,
    tags: ["Twitter", "Marketing", "KOL", "Influencer", "Viral Campaign"],
    tokenTickers: ["$PSX", "$CREATE"],
    psxRequired: "75.00",
    featured: true,
    portfolioMedia: [serviceImages.socialMedia],
    active: true,
  },
  {
    builderId: null,
    title: "Complete Brand Identity Package",
    description: "Professional brand identity design for your Web3 project. Includes logo design, color palette, typography, and brand guidelines optimized for crypto audiences.",
    category: "Graphic Design",
    deliveryTime: "5 days",
    basicPrice: "400.00",
    standardPrice: "800.00",
    premiumPrice: "1500.00",
    basicDescription: "Logo design with 2 concepts and basic brand colors",
    standardDescription: "Complete logo suite with brand guidelines and social media templates",
    premiumDescription: "Full brand identity with logo variations, comprehensive guidelines, and marketing materials",
    basicDeliverables: ["2 logo concepts", "Final logo (vector)", "Color palette", "Basic guidelines"],
    standardDeliverables: ["3 logo concepts", "Logo variations", "Brand guidelines", "Social media templates", "All source files"],
    premiumDeliverables: ["5 logo concepts", "Complete logo suite", "Comprehensive brand book", "Marketing materials", "Social templates", "Website mockups", "All source files"],
    basicDeliveryDays: 7,
    standardDeliveryDays: 5,
    premiumDeliveryDays: 3,
    basicRevisions: 2,
    standardRevisions: 3,
    premiumRevisions: 5,
    tags: ["Logo Design", "Branding", "Identity", "Web3", "Graphic Design"],
    tokenTickers: ["$CREATE"],
    psxRequired: "50.00",
    featured: true,
    portfolioMedia: [serviceImages.logo],
    active: true,
  },
  {
    builderId: null,
    title: "High-Impact Promotional Video",
    description: "Professional promotional video for your crypto project. Includes scripting, editing, motion graphics, and sound design optimized for social media virality.",
    category: "Video Editing",
    deliveryTime: "4 days",
    basicPrice: "600.00",
    standardPrice: "1200.00",
    premiumPrice: "2000.00",
    basicDescription: "30-second promotional video with basic editing and graphics",
    standardDescription: "60-second video with advanced editing, motion graphics, and custom soundtrack",
    premiumDescription: "90-second cinematic video with premium effects, 3D elements, and professional voice-over",
    basicDeliverables: ["30-second video", "Basic editing", "2 revisions", "HD export"],
    standardDeliverables: ["60-second video", "Motion graphics", "Custom soundtrack", "Color grading", "3 revisions", "4K export"],
    premiumDeliverables: ["90-second video", "Advanced VFX", "3D elements", "Professional VO", "Sound design", "5 revisions", "4K export", "Social media cuts"],
    basicDeliveryDays: 5,
    standardDeliveryDays: 4,
    premiumDeliveryDays: 3,
    basicRevisions: 2,
    standardRevisions: 3,
    premiumRevisions: 5,
    tags: ["Video Editing", "Promotional", "Motion Graphics", "Social Media"],
    tokenTickers: ["$PSX"],
    psxRequired: "60.00",
    featured: true,
    portfolioMedia: [serviceImages.video],
    active: true,
  },
];

export async function seedBuilders() {
  try {
    console.log("🌱 Starting builder and service seeding...");

    // Insert builders
    const insertedBuilders = [];
    for (const builderData of sampleBuilders) {
      const [builder] = await db.insert(builders).values(builderData).returning();
      insertedBuilders.push(builder);
      console.log(`✅ Created builder: ${builder.name}`);
    }

    // Insert services and link to builders
    for (let i = 0; i < sampleServices.length; i++) {
      const serviceData = {
        ...sampleServices[i],
        builderId: insertedBuilders[i].id,
      };
      const [service] = await db.insert(services).values(serviceData).returning();
      console.log(`✅ Created service: ${service.title}`);
    }

    console.log("🎉 Successfully seeded builders and services!");
    return { success: true, buildersCount: insertedBuilders.length, servicesCount: sampleServices.length };
  } catch (error) {
    console.error("❌ Error seeding builders:", error);
    throw error;
  }
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedBuilders()
    .then(() => {
      console.log("Seeding complete!");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seeding failed:", error);
      process.exit(1);
    });
}
